# BRIGHTMART SALES FORECAST PROJECT

## Task 1 - Create Variables

In [17]:
product_name = "Wireless Mouse"
selling_price = 12500
units_sold = 180
weekly_sales_target  = 200
forecast_growth_rate = 15
current_stock = 250
minimum_stock_level = 120
product_available = True


2250000


## Task 2 — Calculate Total Weekly Revenue

In [ ]:
weekly_revenue = selling_price * units_sold
print(weekly_revenue)

## Task 3 — Forecast Next Week's Sales

In [21]:
units_sold = 180
forecast_growth_rate = 15

forecasted_sales = units_sold + (units_sold * forecast_growth_rate / 100)
print("Forecasted Sales is" , forecasted_sales)


Forecasted Sales is 207.0


## Task 4 — Forecast Next Week's Revenue

In [22]:
forecasted_revenue = forecasted_sales * selling_price
print(forecasted_revenue)

2587500.0


## Task 5 — Update Current Stock

In [23]:
current_stock -= units_sold
print(current_stock)


70


## Task 6 — Determine if the Sales Target Was Achieved

In [28]:
sales_target_achieved = units_sold >= weekly_sales_target
print(sales_target_achieved)

False


## Task 7 — Check if Restocking is Required

In [26]:
restocking_required = current_stock < minimum_stock_level

print(restocking_required)

True


## Task 8 - Promotion Eligibility

In [31]:
promotion_eligible = product_available and sales_target_achieved

print(promotion_eligible)

False


## Task 9 - Determine if Demand is High

In [35]:
high_demand_forecast = (
    forecasted_sales > 200
    or forecasted_revenue > 2500000
)

print(high_demand_forecast)

True


## Task 10 - Weekly Sales Report

In [37]:
report = f"""
=================================================
        BRIGHTMART SALES FORECAST REPORT
=================================================

Product Name           : {product_name}

Selling Price          : ₦{selling_price:,.2f}

Units Sold This Week   : {units_sold}

Weekly Revenue         : ₦{weekly_revenue:,.2f}

Forecast Growth Rate   : {forecast_growth_rate}%

Forecast Sales         : {forecasted_sales:.0f} Units

Forecast Revenue       : ₦{forecasted_revenue:,.2f}

Current Stock          : {current_stock} Units

Sales Target Achieved  : {sales_target_achieved}

Restocking Required    : {restocking_required}

Product Available      : {product_available}

Promotion Eligible     : {promotion_eligible}

High Demand Forecast   : {high_demand_forecast}

=================================================
"""

print(report)


        BRIGHTMART SALES FORECAST REPORT

Product Name           : Wireless Mouse

Selling Price          : ₦12,500.00

Units Sold This Week   : 180

Weekly Revenue         : ₦2,250,000.00

Forecast Growth Rate   : 15%

Forecast Sales         : 207 Units

Forecast Revenue       : ₦2,587,500.00

Current Stock          : 70 Units

Sales Target Achieved  : False

Restocking Required    : True

Product Available      : True

Promotion Eligible     : False

High Demand Forecast   : True




# Bonus Challenge

In [38]:

# ============================================
# BONUS CHALLENGE - PRODUCT 2
# ============================================

product_name2 = "Bluetooth Speaker"
selling_price2 = 35000
units_sold2 = 95
weekly_sales_target2 = 100
forecast_growth_rate2 = 20
current_stock2 = 140
minimum_stock_level2 = 80
product_available2 = True

# Weekly Revenue
weekly_revenue2 = selling_price2 * units_sold2

# Forecast Sales
forecast_sales2 = units_sold2 + (units_sold2 * forecast_growth_rate2 / 100)

# Forecast Revenue
forecast_revenue2 = forecast_sales2 * selling_price2

# Update Stock
current_stock2 -= units_sold2

# Sales Target Achieved
sales_target_achieved2 = units_sold2 >= weekly_sales_target2

# Restocking Required
restocking_required2 = current_stock2 < minimum_stock_level2

# Promotion Eligiblity
promotion_eligible2 = product_available2 and sales_target_achieved2

# High Demand Forecast
high_demand_forecast2 = (
    forecast_sales2 > 200
    or forecast_revenue2 > 2500000
)

# ============================================
# PRODUCT 2 REPORT
# ============================================

report2 = f"""
=================================================
        BRIGHTMART SALES FORECAST REPORT
=================================================

Product Name           : {product_name2}

Selling Price          : ₦{selling_price2:,.2f}

Units Sold This Week   : {units_sold2}

Weekly Revenue         : ₦{weekly_revenue2:,.2f}

Forecast Growth Rate   : {forecast_growth_rate2}%

Forecast Sales         : {forecast_sales2:.0f} Units

Forecast Revenue       : ₦{forecast_revenue2:,.2f}

Current Stock          : {current_stock2} Units

Sales Target Achieved  : {sales_target_achieved2}

Restocking Required    : {restocking_required2}

Product Available      : {product_available2}

Promotion Eligible     : {promotion_eligible2}

High Demand Forecast   : {high_demand_forecast2}

=================================================
"""

print(report2)


        BRIGHTMART SALES FORECAST REPORT

Product Name           : Bluetooth Speaker

Selling Price          : ₦35,000.00

Units Sold This Week   : 95

Weekly Revenue         : ₦3,325,000.00

Forecast Growth Rate   : 20%

Forecast Sales         : 114 Units

Forecast Revenue       : ₦3,990,000.00

Current Stock          : 45 Units

Sales Target Achieved  : False

Restocking Required    : True

Product Available      : True

Promotion Eligible     : False

High Demand Forecast   : True




# COMPARING BOTH PRODUCTS

## Which product generated more revenue?
- Bluetooth Speaker (Product 2) generated more revenue(₦3,325,000.00) than Wireless Mouse (Product 1).

## Which product has the higher forecasted revenue?
- Bluetooth Speaker (Product 2) has the higher forecasted revenue (₦3,990,000.00).

## Which product requires restocking?
- Wireless Mouse (Product 1) requires restocking because the current stock (70 units) is less than the minimum stock level (120 units).

## Which product is expected to have higher demand next week?
- Product 1 is expected to have higher demand next week because forecast sales is greater than 200.
  
## Which product should management prioritize in next week's marketing campaign?
- The management should prioritize Bluetooth Speaker (Product 2) in next week's marketing campaign because it generates more revenue and has a higher forecasted revenue.
